import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Massyl's website in <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          I'm looking for a work-study contract{' '}
          <code className={styles.code}>in web developemnt</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Across my studies in the field since 2019 &rarr;</h2>
            <p>I built differnt programs</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>I used C, Java & JS, Node & Next &rarr;</h2>
            <p>2D Video Games cars/boats & Websites self-presenting/social-media </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Each hyperlinks above &rarr;</h2>
            <p>Redirects to each of these projects of mine</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>I aspire &rarr;</h2>
            <p>
              to be a freelancer, being near develpors in the field among a company is key
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
